"""Flask web UI for the stock ticker: watchlist, charts, earnings calendar."""

import json
import re
import threading
import time
from calendar import monthrange
from datetime import datetime, timedelta
from datetime import time as dt_time
from pathlib import Path
from zoneinfo import ZoneInfo

import yfinance as yf
from flask import Flask, jsonify, request, send_file, send_from_directory

from collector import (
    db_update_due,
    fetch_history_rows,
    update_database,
    update_earnings,
)
from db import (
    delete_holding,
    get_holdings,
    get_latest_quotes,
    get_meta,
    init_db,
    resolve_db_path,
    set_meta,
    upsert_earnings,
    upsert_holding,
    upsert_prices,
)
from earnings_reminder import get_earnings_info
from indicators import bollinger_bands, macd, rsi
from main import (
    do_earnings_check,
    do_earnings_report_check,
    do_earnings_watch,
    do_premarket_report,
    do_signal_check,
    do_ticker_round,
    is_market_open,
    load_settings,
)
from ticker import WATCHLIST_PATH, fetch_live_quotes

SETTINGS = load_settings()
MARKET_TZ = ZoneInfo(SETTINGS["market_timezone"])

STATIC_DIR = Path(__file__).with_name("static")
SYMBOLS_PATH = STATIC_DIR / "symbols.json"
HEATMAP_PATH = Path(__file__).with_name("sector_heatmap.html")
PREMARKET_PATH = Path(__file__).with_name("premarket_report.html")
SYMBOL_RE = re.compile(r"^[A-Z.]{1,6}$")

app = Flask(__name__, static_folder=str(STATIC_DIR), static_url_path="/static")


def today():
    """Today's date in the market timezone."""
    return datetime.now(MARKET_TZ).date()


def open_db():
    return init_db(resolve_db_path(SETTINGS["db_path"]))


def read_watchlist() -> list[str]:
    """Read tickers from the watchlist file (no exits, unlike ticker.load_watchlist)."""
    if not WATCHLIST_PATH.exists():
        return []
    tickers = []
    for line in WATCHLIST_PATH.read_text().splitlines():
        ticker = line.strip().upper()
        if ticker and not ticker.startswith("#"):
            tickers.append(ticker)
    return tickers


@app.get("/")
def index():
    return send_from_directory(STATIC_DIR, "index.html")


@app.get("/heatmap")
@app.get("/heatmap.html")
def heatmap():
    """Regenerate the sector heatmap with live prices and serve it.

    Falls back to the previously generated file when regeneration fails.
    Lazy import so plotly is only loaded when the heatmap is requested.
    """
    from generate_sector_heatmap import generate_sector_heatmap

    try:
        generate_sector_heatmap(SETTINGS)
    except Exception as exc:
        print(f"Warning: heatmap regeneration failed ({exc})")
    if not HEATMAP_PATH.exists():
        return (
            "Sector heatmap not available — "
            "no holdings with quantity > 0 in the portfolio.",
            404,
        )
    return send_file(HEATMAP_PATH)


@app.get("/premarket")
@app.get("/premarket.html")
def premarket():
    """Serve the pre-market report generated by the notification loop.

    Unlike the heatmap this is not regenerated on request: the report
    snapshots options volume and runs once per weekday at
    premarket_check_time.
    """
    if not PREMARKET_PATH.exists():
        return (
            "Pre-market report not available — it is generated on "
            "weekdays at the configured premarket_check_time.",
            404,
        )
    return send_file(PREMARKET_PATH)


@app.get("/api/config")
def api_config():
    return jsonify({"earnings_remind_days": SETTINGS["earnings_remind_days"]})


def ticker_alerts_enabled() -> bool:
    """UI toggle for Telegram price rounds, persisted in the DB meta table.

    Falls back to the ticker_enabled setting until the toggle is first set.
    """
    conn = open_db()
    try:
        value = get_meta(conn, "ticker_alerts_enabled")
    finally:
        conn.close()
    if value is None:
        return bool(SETTINGS["ticker_enabled"])
    return value == "true"


@app.get("/api/ticker-alerts")
def api_ticker_alerts_get():
    """Current state of the Telegram price-alert toggle."""
    return jsonify(
        {
            "enabled": ticker_alerts_enabled(),
            "interval_seconds": int(SETTINGS["ticker_interval_seconds"]),
        }
    )


@app.post("/api/ticker-alerts")
def api_ticker_alerts_set():
    """Enable or disable Telegram price alerts."""
    data = request.get_json(force=True, silent=True) or {}
    enabled = bool(data.get("enabled"))
    conn = open_db()
    try:
        set_meta(conn, "ticker_alerts_enabled", "true" if enabled else "false")
        conn.commit()
    finally:
        conn.close()
    return jsonify({"ok": True, "enabled": enabled})


@app.get("/api/watchlist")
def api_watchlist():
    return jsonify(read_watchlist())


@app.post("/api/watchlist")
def api_watchlist_add():
    data = request.get_json(force=True, silent=True) or {}
    symbol = str(data.get("symbol", "")).strip().upper()
    if not SYMBOL_RE.match(symbol):
        return jsonify({"error": "invalid symbol"}), 400

    tickers = read_watchlist()
    added = False
    if symbol not in tickers:
        with WATCHLIST_PATH.open("a") as f:
            f.write(f"{symbol}\n")
        added = True

    # Fetch history and earnings immediately so the UI works instantly.
    conn = open_db()
    try:
        try:
            rows = fetch_history_rows(symbol, "1y")
            upsert_prices(conn, symbol, rows)
        except ValueError as exc:
            print(f"Warning: {exc}")
        try:
            info = get_earnings_info(symbol)
            if info is not None:
                _s, earnings_date, eps = info
                upsert_earnings(
                    conn,
                    symbol,
                    earnings_date.isoformat(),
                    eps,
                    datetime.now(MARKET_TZ).isoformat(),
                )
        except ValueError as exc:
            print(f"Warning: {exc}")
        conn.commit()
    finally:
        conn.close()

    return jsonify({"ok": True, "symbol": symbol, "added": added})


@app.delete("/api/watchlist/<symbol>")
def api_watchlist_delete(symbol: str):
    symbol = symbol.strip().upper()
    tickers = read_watchlist()
    if symbol not in tickers:
        return jsonify({"error": "not in watchlist"}), 404

    lines = WATCHLIST_PATH.read_text().splitlines()
    kept = [line for line in lines if line.strip().upper() != symbol]
    WATCHLIST_PATH.write_text("\n".join(kept) + "\n")
    # DB rows are kept deliberately.
    return jsonify({"ok": True, "symbol": symbol})


def search_static(query: str) -> list[dict]:
    """Substring match against the bundled static/symbols.json fallback."""
    if not SYMBOLS_PATH.exists():
        return []
    entries = json.loads(SYMBOLS_PATH.read_text())
    q = query.lower()
    prefix, substring = [], []
    for entry in entries:
        symbol, name = entry["symbol"], entry["name"]
        if symbol.lower().startswith(q):
            prefix.append(entry)
        elif q in symbol.lower() or q in name.lower():
            substring.append(entry)
        if len(prefix) >= 10:
            break
    return (prefix + substring)[:10]


@app.get("/api/quotes")
def api_quotes():
    """Live price and % change vs previous close for each watchlist symbol.

    Batch-fetched from yfinance; symbols that fail fall back to the latest
    values stored in daily_prices.
    """
    symbols = read_watchlist()
    quotes = fetch_live_quotes(symbols)

    missing = [s for s in symbols if s not in quotes]
    if missing:
        conn = open_db()
        try:
            quotes.update(get_latest_quotes(conn, missing))
        finally:
            conn.close()
    return jsonify(quotes)


@app.get("/api/holdings")
def api_holdings():
    """All portfolio holdings as {symbol: {avg_price, quantity}}."""
    conn = open_db()
    try:
        return jsonify(get_holdings(conn))
    finally:
        conn.close()


@app.post("/api/holdings")
def api_holdings_set():
    """Set the avg buy price and quantity for a symbol."""
    data = request.get_json(force=True, silent=True) or {}
    symbol = str(data.get("symbol", "")).strip().upper()
    if not SYMBOL_RE.match(symbol):
        return jsonify({"error": "invalid symbol"}), 400
    try:
        avg_price = float(data.get("avg_price"))
        quantity = float(data.get("quantity"))
    except (TypeError, ValueError):
        return jsonify({"error": "avg_price and quantity must be numbers"}), 400
    if avg_price < 0 or quantity < 0:
        return jsonify({"error": "avg_price and quantity must be >= 0"}), 400

    conn = open_db()
    try:
        upsert_holding(
            conn, symbol, avg_price, quantity, datetime.now(MARKET_TZ).isoformat()
        )
        conn.commit()
    finally:
        conn.close()
    return jsonify({"ok": True, "symbol": symbol})


@app.delete("/api/holdings/<symbol>")
def api_holdings_delete(symbol: str):
    """Remove the holding for a symbol."""
    symbol = symbol.strip().upper()
    conn = open_db()
    try:
        delete_holding(conn, symbol)
        conn.commit()
    finally:
        conn.close()
    return jsonify({"ok": True, "symbol": symbol})


@app.get("/api/search")
def api_search():
    query = (request.args.get("q") or "").strip()
    if not query:
        return jsonify([])

    try:
        results = yf.Search(query, max_results=20).quotes
        matches = []
        for quote in results:
            symbol = (quote.get("symbol") or "").upper()
            name = quote.get("shortname") or quote.get("longname") or ""
            # Only suggest symbols the watchlist POST endpoint would accept
            # (stocks/ETFs; skips futures, forex, foreign-exchange variants).
            if (
                symbol
                and SYMBOL_RE.match(symbol)
                and quote.get("quoteType") in ("EQUITY", "ETF", "INDEX")
            ):
                matches.append({"symbol": symbol, "name": name})
            if len(matches) >= 10:
                break
        if matches:
            return jsonify(matches)
    except Exception as exc:
        print(f"Warning: yfinance search failed ({exc}); using static fallback")

    return jsonify(search_static(query))


def sma(values: list[float | None], window: int) -> list[float | None]:
    """Simple moving average aligned with values; None until enough data."""
    out: list[float | None] = []
    for i in range(len(values)):
        if i + 1 < window:
            out.append(None)
            continue
        chunk = values[i + 1 - window : i + 1]
        if any(v is None for v in chunk):
            out.append(None)
        else:
            out.append(round(sum(chunk) / window, 4))
    return out


@app.get("/api/prices/<symbol>")
def api_prices(symbol: str):
    symbol = symbol.strip().upper()
    conn = open_db()
    try:
        # Full history so indicator EMAs/smoothing warm up correctly,
        # then sliced to the last 260 trading days below.
        rows = conn.execute(
            """
            SELECT date, open, high, low, close, volume FROM daily_prices
            WHERE symbol = ? ORDER BY date
            """,
            (symbol,),
        ).fetchall()
    finally:
        conn.close()

    # Overlay the latest (possibly intraday) bar so the last candle shows
    # the latest price even before the nightly DB update. On weekends and
    # holidays yfinance returns the last trading day, already stored above.
    try:
        live_rows = fetch_history_rows(symbol, "1d")
    except ValueError as exc:
        print(f"Warning: {exc}")
        live_rows = []
    if live_rows:
        live = live_rows[-1]
        if rows and rows[-1][0] == live[0]:
            rows[-1] = live
        elif not rows or live[0] > rows[-1][0]:
            rows.append(live)

    all_closes = [r[4] for r in rows]
    macd_data = macd(all_closes)
    rsi_data = rsi(all_closes)
    bb_mid, bb_up, bb_low = bollinger_bands(all_closes)

    rows = rows[-260:]
    offset = len(all_closes) - len(rows)
    dates = [r[0] for r in rows]
    closes = [r[4] for r in rows]
    return jsonify(
        {
            "symbol": symbol,
            "dates": dates,
            "ohlc": [
                {"time": r[0], "open": r[1], "high": r[2], "low": r[3], "close": r[4]}
                for r in rows
            ],
            "volumes": [r[5] for r in rows],
            "sma5": sma(closes, 5),
            "sma20": sma(closes, 20),
            "sma50": sma(closes, 50),
            "sma200": sma(closes, 200),
            "bb_upper": bb_up[offset:],
            "bb_middle": bb_mid[offset:],
            "bb_lower": bb_low[offset:],
            "macd": macd_data["macd"][offset:],
            "macd_signal": macd_data["signal"][offset:],
            "macd_histogram": macd_data["histogram"][offset:],
            "rsi": rsi_data[offset:],
        }
    )


EARNINGS_RANGES = {"week", "next-week", "month"}


@app.get("/api/earnings")
def api_earnings():
    range_name = request.args.get("range") or "week"
    if range_name not in EARNINGS_RANGES:
        return jsonify({"error": "range must be week, next-week, or month"}), 400

    now = today()
    if range_name == "week":
        start, end = now, now + timedelta(days=6 - now.weekday())
    elif range_name == "next-week":
        start = now + timedelta(days=7 - now.weekday())
        end = start + timedelta(days=6)
    else:  # month: rest of the current calendar month
        start = now
        end = now.replace(day=monthrange(now.year, now.month)[1])

    conn = open_db()
    try:
        rows = conn.execute(
            """
            SELECT symbol, earnings_date, eps_estimate FROM earnings
            WHERE earnings_date BETWEEN ? AND ?
            ORDER BY earnings_date, symbol
            """,
            (start.isoformat(), end.isoformat()),
        ).fetchall()
    finally:
        conn.close()

    return jsonify(
        [
            {"symbol": s, "earnings_date": d, "eps_estimate": e}
            for s, d, e in rows
        ]
    )


@app.get("/api/indicators/<symbol>")
def api_indicators(symbol: str):
    """Bullish/bearish confluence score and per-indicator rows for a symbol.

    The five technical-indicator rows are joined by a Candlestick Pattern
    row and an Options Flow (PCR) row, and the score stacks their bonuses
    on the indicator base exactly like the pre-market report. Computed
    from the local daily_prices table; null when there is not enough
    history (< MIN_BARS closes).
    """
    from generate_indicators_table import (
        MIN_BARS,
        combine_score,
        evaluate_indicators,
    )
    from options_flow import fetch_options_flow
    from patterns import detect_patterns
    from premarket_report import (
        _bars_from_db,
        apply_bonuses,
        options_indicator_row,
        pattern_indicator_row,
    )

    symbol = symbol.strip().upper()
    conn = open_db()
    try:
        bars = _bars_from_db(conn, symbol)
    finally:
        conn.close()
    closes, volumes = bars["closes"], bars["volumes"]
    if len(closes) < MIN_BARS:
        return jsonify(None)
    rows = evaluate_indicators(closes, volumes)
    base = combine_score(rows)

    patterns = detect_patterns(
        bars["opens"], bars["highs"], bars["lows"],
        closes, volumes, dates=bars["dates"],
    )
    rows.append(pattern_indicator_row(patterns))

    flow = fetch_options_flow(symbol)
    rows.append(options_indicator_row(flow))

    score = apply_bonuses(base, patterns, None, flow["pcr"] if flow else None)
    return jsonify(
        {
            "symbol": symbol,
            "score": score["final"],
            "label": score["label"],
            "rows": rows,
        }
    )


@app.get("/api/status/<symbol>")
def api_status(symbol: str):
    symbol = symbol.strip().upper()
    conn = open_db()
    try:
        row = conn.execute(
            "SELECT earnings_date, eps_estimate FROM earnings WHERE symbol = ?",
            (symbol,),
        ).fetchone()
    finally:
        conn.close()

    if not row or not row[0]:
        return jsonify(None)

    earnings_date = datetime.strptime(row[0], "%Y-%m-%d").date()
    days_until = (earnings_date - today()).days
    if days_until < 0:
        return jsonify(None)

    return jsonify(
        {
            "next_earnings": row[0],
            "days_until": days_until,
            "eps_estimate": row[1],
        }
    )


def _notification_loop() -> None:
    """Background notifications, replacing the old stockticker daemon.

    Always on: the daily earnings reminder and earnings-report check at
    earnings_check_time (plus a refresh of the earnings table the
    post-earnings watch relies on), the pre-market portfolio report on
    weekdays at premarket_check_time, and the post-earnings watch every
    minute. The daily price-database refresh (plus the MACD/RSI signal
    check) runs at db_update_time, same as the old daemon. On top of
    that, watchlist price rounds are sent to Telegram
    every ticker_interval_seconds while the UI toggle
    (/api/ticker-alerts) is enabled. All state is DB-driven, so restarts
    neither lose windows nor resend messages.
    """
    check_time = dt_time.fromisoformat(SETTINGS["earnings_check_time"])
    premarket_time = dt_time.fromisoformat(SETTINGS["premarket_check_time"])
    db_update_time = dt_time.fromisoformat(SETTINGS["db_update_time"])
    interval = int(SETTINGS["ticker_interval_seconds"])
    earnings_days = int(SETTINGS["earnings_remind_days"])
    last_check_date = None
    last_premarket_date = None
    last_ticker_round = 0.0
    while True:
        now = datetime.now(MARKET_TZ)
        # BaseException: send_telegram raises SystemExit on API failure,
        # which must not kill this thread.
        try:
            if now.time() >= check_time and last_check_date != now.date():
                last_check_date = now.date()
                update_earnings(SETTINGS)
                do_earnings_check(earnings_days, test=False)
                do_earnings_report_check(SETTINGS, test=False)
            if (
                SETTINGS["premarket_report_enabled"]
                and now.weekday() < 5
                and now.time() >= premarket_time
                and last_premarket_date != now.date()
            ):
                last_premarket_date = now.date()
                do_premarket_report(SETTINGS, test=False)
            do_earnings_watch(SETTINGS, test=False)
            if (
                SETTINGS["db_enabled"]
                and now.time() >= db_update_time
                and db_update_due(SETTINGS, now.date().isoformat())
            ):
                update_database(SETTINGS)
                do_signal_check(SETTINGS, test=False)
            if (
                ticker_alerts_enabled()
                and time.monotonic() - last_ticker_round >= interval
                and (
                    not SETTINGS["ticker_market_hours_only"]
                    or is_market_open(
                        now, SETTINGS["market_open"], SETTINGS["market_close"]
                    )
                )
            ):
                last_ticker_round = time.monotonic()
                do_ticker_round(test=False)
        except BaseException as exc:
            print(f"Warning: notification loop error ({exc})")
        time.sleep(60)


def main() -> None:
    threading.Thread(target=_notification_loop, daemon=True).start()
    app.run(host=SETTINGS["web_host"], port=int(SETTINGS["web_port"]))


if __name__ == "__main__":
    main()
